# Generated by Django 2.2.16 on 2022-12-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221203_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confcode',
            old_name='code',
            new_name='confirmation_code',
        ),
        migrations.RenameField(
            model_name='confcode',
            old_name='user',
            new_name='username',
        ),
    ]
