# Generated by Django 2.2.16 on 2022-12-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221209_0018'),
        ('users', '0003_auto_20221203_2105'),
    ]

    operations = [
    ]
