# Generated by Django 2.2.16 on 2022-12-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221203_1253'),
        ('reviews', '0002_auto_20221209_1338'),
    ]

    operations = [
    ]
